import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    mainContainer: {
        height: '100%',
        width: '100%',
        alignItems: 'center',
    },
    headerIcon: {
        resizeMode: 'contain',
        width: 52,
        height: 41.45,
    },
    logoText: {
        position: 'absolute',
        width: 194,
        height: 55,
        left: 40,
        top: 29,
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 18,
        lineHeight: 24,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        color: '#000000',


    },
    header: {
        height: 60,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    checkIcon: {
        height: 13,
        width: 17,
        left: 2,
        top: 15,
    },
    searchIcon: {
        height: 36,
        width: 36,
        justifyContent: 'center',
        alignItems: 'center',
    },
    searchBar: {
        color: '#9E9E9E',
        justifyContent: 'center',
        alignItems: 'center',
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 11,
        lineHeight: 24,
        textAlign: 'center',
        textTransform: 'capitalize',
    },
    searchBarContainer: {
        position: 'absolute',
        width: 315,
        height: 37,
        left: 14,
        top: 70,
        backgroundColor: '#FFFFFF',
        borderColor: '#6463F9',
        borderStyle: 'solid',
        borderWidth: 1,
        borderRadius: 8,
        flexDirection: 'row',
    },
    storeImage: {
        height: 50,
        width: 60,
    },
    locationIcon: {
        position: 'relative',
        left: 165,
        top: 12,

    },
    title: {
        position: 'absolute',
        width: 349,
        height: 121,
        left: 14,
        top: 125,
    },
    titleText: {
        top: 10,
        fontFamily: 'Open Sans',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: 22,
        lineHeight: 30,
        display: 'flex',
        alignItems: 'center',
        color: '#000000',
    },
    footerContainer: {
        height: 85,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        backgroundColor: '#FFFFFF',
        top: 522,
    },
    footer: {
        //position: 'absolute',
        height: 48,
        width: 311,
        justifyContent: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#6463F9',
        borderRadius: 24,
    },
    footerText: {
        fontFamily: 'Montserrat',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 18,
        lineHeight: 18,
        alignItems: 'center',
        textAlign: 'center',
        color: '#FFFFFF',
    },
    card1: {
        position: 'absolute',
        width: 350,
        height: 134,
        left: 14,
        top: 180,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
    },
    label2: {
        position: 'absolute',
        width: 115,
        height: 18,
        left: 2,
        top: 36,
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: 12,
        lineHeight: 18,
        color: '#000000',
    },
    label3: {
        position: 'absolute',
        width: 74,
        height: 18,
        left: 2,
        top: 57,
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: 12,
        lineHeight: 18,
        color: '#000000',
    },

    penIcon: {
        height: 20,
        width: 20,
        left: 274,
        top: 79,
    },
    trashIcon: {
        height: 20,
        width: 14,
        left: 320,
        top: 58,
    },
});


export default styles;