import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    mainContainer: {
        height: '100%',
        width: '100%',
        alignItems: 'center',
    },
    headerContainer: {
        width: '100%',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
    },
    header: {
        //position: 'absolute',
        height: 60,
        width: 325,
        left: -22,
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerIcon: {
        height: 41.45,
        width: 52,
        resizeMode: 'contain',
    },
    logoText: {
        width: 194,
        marginLeft: 10,
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 18,
        lineHeight: 24,
        color: '#000000',
    },
    carouselContainer: {
        width: '100%',
    },
    searchBarContainer: {
        height: 40,
        width: 325,
        left: -15,
        marginBottom: 10,
        borderRadius: 8,
        borderColor: '#6463F9',
        flexDirection: 'row',
        borderWidth: 1,
    },
    filterIcon: {
        height: 30,
        width: 20,
        resizeMode: 'contain',
    },
    filtersContainer: {
        height: 60,
        left: 14,
        marginTop: 10,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        backgroundColor: '#70CDAC',
    },
    searchIcon: {
        height: 36,
        width: 36,
        justifyContent: 'center',
        alignItems: 'center',
    },
    searchBarText: {
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 11,
        color: '#9E9E9E',
    },
    filterText: {
        color: 'white',
        paddingLeft: 3,
        fontSize: 17,
    },
    input: {
        //position: 'absolute',
        //left: 10,
        //right: '10%',
        //top: 23,
        //bottom: 10,
        width: 350,
        height: 42,
        marginTop: 5,
        //background: '#F9F9F9',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#D1D1D1',
        borderRadius: 12,
        color: '#151515'
    },
    inputName: {
        //position: 'absolute',
        //left: 10,
        //right: '10%',
        //top: 23,
        //bottom: 10,
        width: 160,
        marginTop: 5,
        //background: '#F9F9F9',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#D1D1D1',
        borderRadius: 12,
        color: '#151515'
    },
    inputLastName: {
        //position: 'absolute',
        flexDirection: 'row',
        left: 190,
        //right: '10%',
        top: -57,
        //bottom: 10,
        width: 160,
        marginTop: 5,
        //background: '#F9F9F9',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#D1D1D1',
        borderRadius: 12,
        color: '#151515'
    },
    form: {
        flex: 1,
        padding: 10,
        //position: 'absolute',
        width: 375,
        height: 767,
        top: 35,
        backgroundColor: '#FFFFFF',
        borderRadius: 16.5,
    },
    formtextContainer: {
        width: 350,
        height: 18,
        marginTop: 23,
        left: 12,
    },
    formtext: {
        position: 'absolute',
        height: 18,
        left: 0,
        right: 0,
        top: 0,

        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '800',
        fontSize: 12,
        lineHeight: 18,
        color: '#151515',
    },
    fullname: {
        width: 350,
        height: 18,
        left: 12,
    },
    fullnameinput: {
        width: 350,
        height: 0,
        marginTop: 5,
        flex: 1,
        flexDirection: 'row',
    },
    nametextContainer: {
        width: 160,
        height: 18,
        marginTop: 23,
        left: 12,
    },
    nametext: {
        position: 'absolute',
        height: 18,
        left: 0,
        right: 0,
        top: 0,

        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '800',
        fontSize: 12,
        lineHeight: 18,
        color: '#151515',
    },
    lastnametext: {
        position: 'absolute',
        height: 18,
        left: 190,
        right: 0,
        top: 0,

        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '800',
        fontSize: 12,
        lineHeight: 18,
        color: '#151515',
    },
    footerContainer: {
        height: 85,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        backgroundColor: '#FFFFFF',
    },
    footer: {
        //position: 'absolute',
        height: 48,
        width: 311,
        justifyContent: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#6463F9',
        borderRadius: 24,
    },
    footerText: {
        fontFamily: 'Montserrat',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 18,
        lineHeight: 18,
        alignItems: 'center',
        textAlign: 'center',
        color: '#FFFFFF',
    },
    button: {
        borderColor: 'white',
        paddingVertical: 5,
        alignItems: 'center',
        height: 40,
        justifyContent: 'space-evenly',
        paddingHorizontal: 20,
        flexDirection: 'row',
        borderWidth: 1,
        borderRadius: 20,
    },
    textContainer: {
        height: 50,
        marginTop: 10,
        width: 370,
        flexDirection: 'row',
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerText: {
        color: 'black',
        fontSize: 17,
    },
    storeImage: {
        height: 50,
        width: 60,
    },
});

export default styles;