import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    mainContainer: {
        height: '100%',
        width: '100%',
        alignItems: 'center',
    },
    bodyText: {
        //position: 'absolute',
        flex: 1,
        alignItems: 'center',
        width: 200,
        top: 130,
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: 26,
        lineHeight: 31,
        textAlign: 'center',
        letterSpacing: -0.005,
        color: '#000000',
    },

    filterIcon: {
        height: 30,
        width: 20,
        resizeMode: 'contain',
    },
    filterText1: {
        color: '#FFFFFF',
        paddingLeft: 10,
        fontSize: 17,
    },
    filterText2: {
        color: '#807c7c',
        paddingLeft: 10,
        fontSize: 17,
    },
    button: {
        alignItems: 'center',
        height: 25,
        flexDirection: 'row',
    },
    button1: {
        position: 'absolute',
        width: 285,
        height: 51,
        left: 37,
        top: 450,
        padding: 1,
        backgroundColor: '#1877F2',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    button2: {
        position: 'absolute',
        width: 281,
        height: 51,
        left: 37,
        top: 533,
        padding: 1,
        backgroundColor: '#FFFFFF',
        borderRadius: 30,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerIcon: {
        resizeMode: 'contain',
        width: 52,
        height: 41.45,
    },
    logoText: {
        position: 'absolute',
        width: 194,
        height: 55,
        left: 40,
        top: 29,
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 18,
        lineHeight: 24,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        color: '#000000',


    },
    header: {
        height: 60,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },

    searchIcon: {
        height: 36,
        width: 36,
        justifyContent: 'center',
        alignItems: 'center',
    },
    searchBar: {
        color: '#9E9E9E',
        justifyContent: 'center',
        alignItems: 'center',
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 11,
        lineHeight: 24,
        textAlign: 'center',
        textTransform: 'capitalize',
    },
    searchBarContainer: {
        position: 'absolute',
        width: 315,
        height: 37,
        left: 14,
        top: 70,
        backgroundColor: '#FFFFFF',
        borderColor: '#6463F9',
        borderStyle: 'solid',
        borderWidth: 1,
        borderRadius: 8,
        flexDirection: 'row',
    },
    storeImage: {
        height: 50,
        width: 60,
    },
    locationIcon: {
        position: 'relative',
        left: 165,
        top: 12,

    },
    title: {
        position: 'absolute',
        width: 349,
        height: 121,
        left: 14,
        top: 125,
    },
    titleText: {
        top: 10,
        fontFamily: 'Open Sans',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: 22,
        lineHeight: 30,
        display: 'flex',
        alignItems: 'center',
        color: '#000000',
    },
    middleImage: {
        position: 'absolute',
        width: 348,
        height: 192,
        left: 14,
        top: 200,
    },
    middle: {
        position: 'absolute',
        width: 345,
        height: 22,
        left: 10,
        top: 410,
    },
    middleText: {
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '300',
        fontSize: 16,
        textAlign: 'center',
        letterSpacing: -0.005,
        color: '#000000',
    },
});


export default styles;
