import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    mainContainer: {
        height: '100%',
        width: '100%',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    topImage: {
        width: '100%',
        height: 365,
        marginTop: 0,
    },
    header: {
        height: 114,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#FFFFFF',
        marginTop: 0,
        
    },
    headerIcon: {
        resizeMode: 'contain',
        marginLeft: 36,
    },
    logoText: {
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: 18,
        lineHeight: 24,
        textAlign: 'center',
        color: '#000000',
        marginLeft: '15%',
    },

    bottomImage: {
        width: '100%',
        height: 670,
        margin: 0,
    },
    titleContainer: {
        marginLeft: 21,
        marginTop: 0,
        width: 219,
        top: 36,
    },
    title: {
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '700',
        fontSize: 24,
        lineHeight: 36,
        textAlign: 'center',
        letterSpacing: 0.03,
        color: '#000000',
    },
    form: {
        flex: 1,
        padding: 20,
        //position: 'absolute',
        width: 354,
        //height: 1000,
        marginTop: 50,
        marginBottom: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 16.5,
        alignSelf: 'center',
    },
    formtextContainer: {
        width: 319,
        height: 20,
        marginTop: 23,
        marginLeft: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    formtext: {
        position: 'absolute',
        height: 18,
        left: 0,
        right: 0,
        top: 0,
    
        fontFamily: 'Rubik',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 18,
        lineHeight: 18,
        color: '#000000',
    },
    input: {
        //position: 'absolute',
        //left: 10,
        //right: '10%',
        //top: 23,
        //bottom: 10,
        width: '100%',
        height: 42,
        paddingLeft: 15,
        marginTop: 10,
        //background: '#F9F9F9',
        backgroundColor: '#F8FFFE',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#70CDAC',
        borderRadius: 12,
        color: '#151515'
    },
    descInput: {
        //position: 'absolute',
        //left: 10,
        //right: '10%',
        //top: 23,
        //bottom: 10,
        width: '100%',
        height: 126,
        paddingLeft: 15,
        marginTop: 10,
        marginBottom: 10,
        //background: '#F9F9F9',
        backgroundColor: '#F8FFFE',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#70CDAC',
        borderRadius: 12,
        color: '#151515',
        textAlignVertical: 'top',
    },
    date: {
        //position: 'absolute',
        //left: 10,
        //right: '10%',
        //top: 23,
        //bottom: 10,
        width: '100%',
        height: 42,
        paddingLeft: 15,
        marginTop: 10,
        //background: '#F9F9F9',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#70CDAC',
        borderRadius: 6,
        color: '#151515',
        alignItems: 'center',
        flexDirection: 'row',
    },
    dateText: {
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 18,
        //lineHeight: 28,
        color: '#242731',
    },
    down: {
        marginLeft: '35%',
    },
    squareCheck: {
        width: 20,
        height: 20,
        backgroundColor: '#F9F9F9',
        borderWidth: 1.5,
        borderStyle: 'solid',
        borderColor: '#D1D1D1',
        borderRadius: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    line1: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        marginTop: 12,
    },
    subtitleContainer1: {
        //marginLeft: 21,
        marginTop: 30,
        width: 296,
        //top: 36,
    },
    optionContainer: {
        //position: 'absolute',
        //left: 10,
        //right: '10%',
        //top: 23,
        //bottom: 10,
        width: '50%',
        height: 28,
        //paddingLeft: 15,
        marginTop: 15,
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    checkText: {
        marginLeft: 10,
        //width: 40,
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 18,
        lineHeight: 21,
        color: '#000000',
    },
    checkTextSmall: {
        marginLeft: 10,
        //width: 40,
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 14,
        lineHeight: 21,
        color: '#000000',
    },
    line: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
    },
    subtitleContainer: {
        //marginLeft: 21,
        marginTop: 15,
        width: 296,
        //top: 36,
    },
    subtitle: {
        
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 13,
        lineHeight: 18,
        letterSpacing: 0.03,
        color: '#242731',
    },
    filterIcon: {
        height: 30,
        width: 20,
        resizeMode: 'contain',
    },
    filterText: {
        color: 'white',
        paddingLeft: 10,
        fontSize: 17,
    },
    button: {
        alignItems: 'center',
        height: 25,
        flexDirection: 'row',

    },
    button1: {
        position: 'absolute',
        width: 323,
        height: 58,
        left: 29,
        top: 325,
        backgroundColor: '#70CDAC',
        borderRadius: 30,
        justifyContent: 'space-evenly',
        alignItems: 'center',

    },
    button2: {
        position: 'absolute',
        width: 323,
        height: 58,
        left: 29,
        top: 403,
        backgroundColor: '#1877F2',
        borderRadius: 30,
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    empty: {
        height: 50,
    },
    footerContainer: {
        position: 'absolute',
        height: 85,
        width: '100%',
        bottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        backgroundColor: '#FFFFFF',
        elevation: 10,
      },
      footer: {
        //position: 'absolute',
        height: 48,
        width: 311,
        justifyContent: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#6463F9',
        borderRadius: 24,
      },
      footerText: {
        fontFamily: 'Montserrat',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: 18,
        lineHeight: 18,
        alignItems: 'center',
        textAlign: 'center',
        color: '#FFFFFF',
      },
});

export default styles;
