import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    height: '100%',
    width: '100%',
    alignItems: 'center',
  },
  headerContainer: {
    height: 85,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    backgroundColor: '#70CDAC',
  },
  header: {
    //position: 'absolute',
    height: 32,
    width: 343,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    position: 'absolute',
    left: 3,
    //right: 3,
    //top: '16.67%',
    //bottom: '19.11%',
  },
  headerText: {
    //position: 'absolute',
    //height: 29,
    //top: 20,
    
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 24,
    lineHeight: 29,
    alignItems: 'center',
    textAlign: 'center',
    color: '#FFFFFF',
  },
  scrollContainer: {
    height: '100%',
    width: '100%',
    //alignItems: 'center',
  },
  form: {
    //flex: 1,
    padding: 20,
    //position: 'absolute',
    width: '95%',
    height: '74%',
    marginTop: 35,
    marginBottom: 35,
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16.5,
  },
  titleContainer: {
    width: '100%',
    height: 63,
    //marginTop: 23,
  },
  title2Container: {
    width: '100%',
    height: 63,
    marginTop: 20,
    //marginTop: 23,
  },
  title: {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 33,
    color: '#151515',
  },
  subtitle: {
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    color: '#A9A9A9',
  },
  searchIcon: {
    height: 36,
    width: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchBar: {
    color: '#9E9E9E',
  },
  optionContainer: {
    //position: 'absolute',
    //left: 10,
    //right: '10%',
    //top: 23,
    //bottom: 10,
    width: '100%',
    height: 42,
    paddingLeft: 15,
    marginTop: 40,
    backgroundColor: '#F9F9F9',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  option2Container: {
    //position: 'absolute',
    //left: 10,
    //right: '10%',
    //top: 23,
    //bottom: 10,
    width: '100%',
    height: 42,
    paddingLeft: 15,
    marginTop: 30,
    backgroundColor: '#F9F9F9',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  circleCheck: {
    resize:'contain',
  },
  company: {
    marginLeft: 20,
    //width: 40,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '800',
    fontSize: 12,
    lineHeight: 18,
    color: '#000000',
  },
  price: {
    //width: 54,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '800',
    fontSize: 12,
    lineHeight: 18,
    color: '#6463F9',
  },
  text: {
    //width: 100,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '800',
    fontSize: 12,
    lineHeight: 18,
    color: '#000000',
  },
  input: {
    //position: 'absolute',
    //left: 10,
    //right: '10%',
    //top: 23,
    //bottom: 10,
    width: '100%',
    height: 126,
    paddingLeft: 15,
    marginTop: 5,
    //background: '#F9F9F9',
    backgroundColor: '#F9F9F9',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
    borderRadius: 12,
    color: '#151515',
    textAlignVertical: 'top',
  },
  formtextContainer: {
    width: 319,
    height: 18,
    marginTop: 23,
  },
  formtext: {
    position: 'absolute',
    height: 18,
    left: 0,
    right: 0,
    top: 0,

    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '800',
    fontSize: 12,
    lineHeight: 18,
    color: '#151515',
  },
  delivercheck: {
    //position: 'absolute',
    //left: 10,
    //right: '10%',
    //top: 23,
    //bottom: 10,
    width: '100%',
    height: 35,
    marginTop: 30,
    paddingLeft: 15,
    flexDirection: 'row',
    //background: '#F9F9F9',
    backgroundColor: '#F9F9F9',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
    borderRadius: 12,
    color: '#151515',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  delivercheck2: {
    //position: 'absolute',
    //left: 10,
    //right: '10%',
    //top: 23,
    //bottom: 10,
    width: '100%',
    height: 35,
    marginTop: 20,
    paddingLeft: 15,
    flexDirection: 'row',
    //background: '#F9F9F9',
    backgroundColor: '#F9F9F9',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
    borderRadius: 12,
    color: '#151515',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  deliverchecktext: {
    marginLeft: 5,
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 12,
    color: '#151515',
  },
  squareCheck: {
    width: 20,
    height: 20,
    backgroundColor: '#F9F9F9',
    borderWidth: 1.5,
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textContainer: {
    height: 50,
    marginTop: 10,
    width: 370,
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerContainer: {
    position: 'absolute',
    height: 85,
    width: '100%',
    flexDirection: 'row',
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    backgroundColor: '#FFFFFF',

    shadowColor: '#3A4C82',
    shadowOffset: {width:0 ,height:-19},
    shadowOpacity: 0.0722656,
    shadowRadius: 38,
  },
  footer: {
    //position: 'absolute',
    height: 48,
    width: 311,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#70CDAC',
    borderRadius: 24,
  },
  footerText: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 18,
    alignItems: 'center',
    textAlign: 'center',
    color: '#FFFFFF',
  },
  checkboxContainer: {
    flexDirection: "row",
    marginBottom: 20,
  },
  checkbox: {
    alignSelf: "center",
  },
  label: {
    margin: 8,
  },
});

export default styles;
